[package]
name = "hairbraint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22" # eframe makes it easier to run an egui app
diesel = { version = "2.1", features = ["sqlite"] }
